### ISSUE TITLE
Restart loop occurring in Docker 'nginx: [emerg] invalid port in "443:-443}"'

### ISSUE THREAD

**Issue by andrewodri** [fsouza/docker-ssl-proxy#7]
Just noticed that the image breaking in my particular case since the most recent update. Here is how it defined in my `docker-compose.yml` file:

```
services:
  proxy:
    image: fsouza/docker-ssl-proxy
    ports:
      - "443:443"
    restart: always
    environment:
      DOMAIN: localhost
      TARGET_PORT: 80
      TARGET_HOST: wordpress
```

Here is the output from `docker logs docker-ssl-proxy`:

```
Generating RSA private key, 2048 bit long modulus
.............................+++
....................................................................................................................................................................+++
e is 65537 (0x10001)
Generating RSA private key, 2048 bit long modulus
................................................................................................................+++
............+++
e is 65537 (0x10001)
Signature ok
subject=/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost
Getting CA Private Key
nginx: [emerg] invalid port in "443:-443}" of the "listen" directive in /etc/nginx/nginx.conf:11
```

The image was working perfectly; prior to today I did a fresh pull about 3-4 days ago.
